---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-cached1-job
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 9000
        runAsGroup: 9000
      containers:
      - name: build
        image: alpine:3.13
        command: ["/bin/sh", "-c"]
        args:
        - |
            set -ex
            ls -la $CACHEDIR
            mktemp -d -p $CACHEDIR
            ([ -f $CACHEDIR/date ] || date > $CACHEDIR/date) && cat $CACHEDIR/date
        env:
        - name: CACHEDIR
          value: /cache
        volumeMounts:
        - mountPath: /cache
          name: cache
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: test-cached1-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-cached1-pvc
  annotations:
    k8storagex.mgoltzsche.github.com/cache-name: test-project
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: cache
