---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-hostdir-job
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 5000
        runAsGroup: 5000
      containers:
      - name: build
        image: alpine:3.13
        command: ["/bin/sh", "-c"]
        args:
        - |
            set -ex
            ls -la $DATADIR
            mktemp -d -p $DATADIR
            date > $DATADIR/date
        env:
        - name: DATADIR
          value: /data
        volumeMounts:
        - mountPath: /data
          name: hostdir
      volumes:
      - name: hostdir
        persistentVolumeClaim:
          claimName: test-hostdir-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-hostdir-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: host-directory
