apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: local-path-provisioner
        image: local-path-provisioner:v0.0.17-privileged-patch
        # patched rancher/local-path-provisioner:v0.0.17 to support --privileged option
        imagePullPolicy: IfNotPresent
        command:
        - local-path-provisioner
        - --debug
        - start
        - --config
        - /etc/config/config.json
        - --configmap-name
        - cached-local-path-config
        - --provisioner-name
        - mgoltzsche.github.com/cache-provisioner
        - --service-account-name
        - cached-local-path-provisioner-service-account
        - --helper-image
        - mgoltzsche/podman:1.9.3
        - --privileged
