apiVersion: v1
kind: Pod
metadata:
  name: caching-build
  labels:
    buildname: buildx
spec:
  restartPolicy: Never
  containers:
  - name: sync
    image: mgoltzsche/podman:2.0.4
    args:
    - /bin/sh
    - -c
    - |
        set -ex
        echo hello1
        ([ -f /cache/date ] || date > /cache/date) && cat /cache/date
        cat - > /podman/.config/containers/storage.conf <<-EOF
          [storage]
          graphroot = "/cache/containers"
          driver = "overlay"
          [storage.options.overlay]
          mount_program = "/usr/local/bin/fuse-overlayfs"
        EOF
        podman run --rm alpine:3.12 echo hello from nested container || true
        podman rm -afi --volumes
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: "/cache"
      name: cache
  volumes:
  - name: cache
    persistentVolumeClaim:
      claimName: build-cache
  affinity:
    nodeAffinity:
      # pod SHOULD run on particular node
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            # here a group of build nodes would be specified by label
            - kube-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-cache
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: cached-local-path
#  selector: 
#    matchLabels: 
#      cache-group: default