namePrefix: k8storagex-
resources:
- serviceaccount.yaml
- manager.yaml
commonLabels:
  app.kubernetes.io/component: k8storagex-manager
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
images:
- name: mgoltzsche/k8storagex-controller-manager
  newName: docker.io/mgoltzsche/k8storagex-controller-manager
  newTag: 0.1.1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
