resources:
- manager.yaml
commonLabels:
  app.kubernetes.io/component: cache-manager
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: manager-config
  files:
  - controller_manager_config.yaml
