namePrefix: storage-
resources:
- serviceaccount.yaml
- manager.yaml
commonLabels:
  app.kubernetes.io/component: cache-manager
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
images:
- name: mgoltzsche/cache-manager
  newName: docker.io/mgoltzsche/cache-manager
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
