apiVersion: registry.mgoltzsche.github.com/v1alpha1
kind: ImageRegistry
metadata:
  name: cache-registry
  namespace: cache-storage
spec:
  replicas: 1
  tls: {}
  persistentVolumeClaim:
    storageClassName: standard
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
---
apiVersion: registry.mgoltzsche.github.com/v1alpha1
kind: ImagePushSecret
metadata:
  name: cache-registry
  namespace: cache-storage
spec:
  registryRef:
    name: cache-registry
