apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cache-viewer-role
rules:
- apiGroups:
  - cache-provisioner.mgoltzsche.github.com
  resources:
  - caches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache-provisioner.mgoltzsche.github.com
  resources:
  - caches/status
  verbs:
  - get
