apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache-provisioner.mgoltzsche.github.com
  resources:
  - caches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache-provisioner.mgoltzsche.github.com
  resources:
  - caches/finalizers
  verbs:
  - update
- apiGroups:
  - cache-provisioner.mgoltzsche.github.com
  resources:
  - caches/status
  verbs:
  - get
  - patch
  - update
