# permissions for end users to edit storageprovisioners.
apiVersion: rbac.authorization.k8s.io/v1 # permissions for end users to edit storageprovisioners.
kind: ClusterRole
metadata:
  name: storageprovisioner-editor-role
rules:
- apiGroups:
  - k8storagex.mgoltzsche.github.com.k8storagex.mgoltzsche.github.com
  resources:
  - storageprovisioners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8storagex.mgoltzsche.github.com.k8storagex.mgoltzsche.github.com
  resources:
  - storageprovisioners/status
  verbs:
  - get
