# permissions for end users to view storageprovisioners.
apiVersion: rbac.authorization.k8s.io/v1 # permissions for end users to view storageprovisioners.
kind: ClusterRole
metadata:
  name: storageprovisioner-viewer-role
rules:
- apiGroups:
  - k8storagex.mgoltzsche.github.com.k8storagex.mgoltzsche.github.com
  resources:
  - storageprovisioners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8storagex.mgoltzsche.github.com.k8storagex.mgoltzsche.github.com
  resources:
  - storageprovisioners/status
  verbs:
  - get
