apiVersion: v1
kind: Pod
metadata:
  name: helper-pod
spec:
  containers:
  - name: helper
    image: mgoltzsche/cache-provisioner-helper:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      hostPID: true
    volumeMounts:
    - name: data
      mountPropagation: Bidirectional
