apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: local-path-provisioner
        image: local-path-provisioner:v0.0.19-pod-patch
        # patched rancher/local-path-provisioner:v0.0.17 to support --privileged option
        imagePullPolicy: IfNotPresent
        env:
        - name: PROVISIONER_NAME
          value: mgoltzsche.github.com/cache-provisioner
        - name: PVC_ANNOTATION
          value: cache-provisioner.mgoltzsche.github.com
        - name: PVC_ANNOTATION_REQUIRED
          value: cache-provisioner.mgoltzsche.github.com/cache-name
