# The following patch adds a directive for certmanager to inject CA into the CRD
apiVersion: apiextensions.k8s.io/v1 # The following patch adds a directive for certmanager to inject CA into the CRD
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
  name: storageprovisioners.k8storagex.mgoltzsche.github.com.k8storagex.mgoltzsche.github.com
