# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1 # The following patch enables a conversion webhook for the CRD
kind: CustomResourceDefinition
metadata:
  name: storageprovisioners.k8storagex.mgoltzsche.github.com.k8storagex.mgoltzsche.github.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: system
          name: webhook-service
          path: /convert
