namespace: cache-storage
namePrefix: cache-
commonLabels:
  app.kubernetes.io/component: cache-provisioner
resources:
#- github.com/rancher/local-path-provisioner/deploy?ref=v0.0.17
# Using patched version for now until PR is merged: https://github.com/rancher/local-path-provisioner/pull/166
- github.com/mgoltzsche/local-path-provisioner/deploy?ref=98183533215ddb590d644eb50260a2dd04a100fa
- serviceaccount.yaml
patchesStrategicMerge:
- operator-patch.yaml
- config.yaml
#- local_path_provisioner_rolebinding.yaml
patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: local-path-storage
  patch: |-
    - op: replace
      path: /metadata/name
      value: cache-storage
- target:
    group: storage.k8s.io
    version: v1
    kind: StorageClass
    name: local-path
  patch: |-
    - op: replace
      path: /metadata/name
      value: cache
    - op: replace
      path: /provisioner
      value: mgoltzsche.github.com/cache-provisioner
