apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: local-path-provisioner
        # Using patched version for now until PR is merged: https://github.com/rancher/local-path-provisioner/pull/166
        image: mgoltzsche/local-path-provisioner:0.0.19-helper-pod-patch
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIGMAP_NAME
          value: cache-local-path-config
        - name: SERVICE_ACCOUNT_NAME
          value: cache-manager
        - name: PROVISIONER_NAME
          value: mgoltzsche.github.com/cache-provisioner
        - name: PVC_ANNOTATION
          value: cache-provisioner.mgoltzsche.github.com
        - name: PVC_ANNOTATION_REQUIRED
          value: cache-provisioner.mgoltzsche.github.com/cache-name
