apiVersion: v1
kind: ConfigMap
metadata:
  name: render-kustomization
  annotations:
    config.kubernetes.io/function: |
      container:
        image: mgoltzsche/kustomizr:1.0.1
        network: true
    config.kubernetes.io/local-config: 'true'
data:
  path: default
  outputPath: static/default/manifest.yaml
  '--reorder': none
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: render-kustomization
  annotations:
    config.kubernetes.io/function: |
      container:
        image: mgoltzsche/kustomizr:1.0.1
        network: true
    config.kubernetes.io/local-config: 'true'
data:
  path: minikube
  outputPath: static/minikube/manifest.yaml
  '--reorder': none
