apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        image: mgoltzsche/pvc-remover:0.1.1
        args:
        - --enable-leader-election
        - --storage-class=cache
