name: Build & Test

on:
  # Trigger the workflow on push or pull request on master branch
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build & test binaries
      run: make all test

    - name: Build images
      run: make images

    - name: Generate static manifests
      run: make static-manifests

    - name: Test e2e
      run: make test-e2e-kind

    - name: Require git tracked files to be unchanged
      run: make check-repo-unchanged
