name: Semantic release

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Test
      run: make all test static-manifest test-e2e-minikube

    - name: Log into GitHub registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Log into DockerHub registry
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login docker.io -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Install semantic-release
      run: npm install semantic-release@17.4.2 @semantic-release/exec@5.0.0 @semantic-release/git@9.0.0

    - name: Release eventually
      run: npx semantic-release

